In [1]:
import torch
import numpy as np

Создайте случайный FloatTensor размера 3x4x5

In [3]:
random_ft = torch.randn(3, 4, 5)

Выведите его форму (shape)

In [5]:
random_ft.size()

torch.Size([3, 4, 5])

Приведите его к форме 6х10

In [7]:
random_ft = random_ft.reshape(6, 10)
random_ft.size()

torch.Size([6, 10])

Создайте случайный IntTensor размера 10

In [9]:
random_iv = torch.randint(10, size = (10,))

Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [11]:
el_mul_ft_iv = random_ft * random_iv

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [15]:
mat_mul_ft_ft = torch.matmul(random_ft, random_ft.T)
mat_mul_ft_ft.size()

torch.Size([6, 6])

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [31]:
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)
y = x**3 + z - 75 * t
y.backward()
grad_y = torch.tensor([x.grad, z.grad, t.grad])
grad_y

tensor([  3.,   1., -75.])

Создайте единичный тензор размера 5x6

In [32]:
ones_t = torch.ones(5, 6)
ones_t

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

Переведите его в формат numpy

In [34]:
ones_t_np = ones_t.numpy()
ones_t_np

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)